### ISSUE TITLE
MLIRConfig.cmake

### ISSUE THREAD

**Issue by Ravenwater** [makslevental/mmlir#13]
I don't know what the best-known-method is for CMake projects that need to pull in a local directory, but would an MLIRConfig.cmake be helpful here?

![image](https://github.com/user-attachments/assets/0b217ce3-c403-4f9e-8afd-955abbd7690a)

**Comment by makslevental** [comment]
MLIRConfig.cmake is part of the upstream LLVM/MLIR distribution (it's in `lib/cmake/mlir`) so either you don't have the distribution or you don't have the `MLIR_DIR/CMAKE_PREFIX_PATH` set correctly.

**Comment by Ravenwater** [comment]
Can I do it with just the LLVM repo and build from there? 

I have not yet encountered the documentation that talks about installing a distribution on Windows. Which is what I'll start Googling right now

**Comment by makslevental** [comment]
> Can I do it with just the LLVM repo and build from there?

You can - it's in the same place under the build dir I believe. 

> I have not yet encountered the documentation that talks about installing a distribution on Windows.

There's nothing special about a distro - it doesn't need to be installed in program files or whatever - it's just a folder with all of the stuff. For example download any of the Windows tars here

https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.6

or here

https://github.com/llvm/eudsl/releases/tag/llvm

And you'll find the MLIRConfig.cmake

**Comment by Ravenwater** [comment]
I went with the install from my local clone, which dumps it in the `Program Files (x86)` dir.

What is the LLVM_EXTERNAL_LIT configuration, which is my next hurdle:
![image](https://github.com/user-attachments/assets/8bcc8ef7-a066-4cf0-8944-13550a3c6a90)



And I did confirm that the whole hierarchy is present in the build directory, so that is good to know, thank you.

**Comment by makslevental** [comment]
lit is an internal llvm-project tool you can get it from the clone https://github.com/llvm/llvm-project/tree/main/llvm/utils/lit

**Comment by Ravenwater** [comment]
Mmm, it does appear to trigger a fail during generation:

![image](https://github.com/user-attachments/assets/a02cec05-7448-4850-961c-900a0dc77db2)

**Comment by Ravenwater** [comment]
Looks like it didn't get built as part of my MLIR build.

**Comment by makslevental** [comment]
This is FileCheck which is used by lit. You need to build your distro with `LLVM_INSTALL_UTILS=ON` to get that in your distribution.

**Comment by Ravenwater** [comment]
Just found build switch, let me give that a whirl

**Comment by Ravenwater** [comment]
That cleared everything up nicely:

![image](https://github.com/user-attachments/assets/40167eb5-58f0-4a56-97e7-29a3aabece53)
