### ISSUE TITLE
Missing header: Rewrite.h

### ISSUE THREAD

**Issue by jbulow** [makslevental/mmlir#9]
Following the instruction I end up with the following error when running ninja:

```
<prefix>/mmlir/mlir/src/python/MLIRPythonExtension.Core/MainModule.cpp:14:10: fatal error: Rewrite.h: No such file or directory
   14 | #include "Rewrite.h"
      |          ^~~~~~~~~~~
```

**Comment by makslevental** [comment]
This is due to a breakage upstream that I just reverted https://github.com/llvm/llvm-project/pull/95226. It will take a couple of hours to filter through.

**Comment by makslevental** [comment]
Should be fixed now. Feel free to reopen if something else goes wrong for you.
